### ISSUE TITLE
Addition of hacktoberfest

### ISSUE THREAD

**Issue by ishgary** [aryasoni98/HacktoberfestPR2020#111]
Please add your repo to this hacktoberfest by using its tag

**Comment by iamvs-2002** [comment]
#hacktoberfest

**Comment by ishgary** [comment]
I didn't mean that 
you need to add this repo to hacktoberfest

**Comment by iamvs-2002** [comment]
Ohh, 2nd way of doing that is to add a label "hacktoberfest-accepted" to the Pull request.
